import { writeFile, readFile } from "fs/promises";

// This did:webs MUST match the identifier that will be generated by the credential script.
const VLEI_DID_WEBS =
  "did:webs:mock-qvi.local:Eabc123_placeholder_legal_entity_aid";

async function createIdentity() {
  console.log("🚀 Creating a new TWIN ID...");

  try {
    // Call the twin-service API to create a real DID
    const response = await fetch("http://localhost:3001/create-did", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    const result = await response.json();
    if (!result.success) {
      throw new Error(result.error || "Failed to create DID");
    }

    const realDid = result.did.id;
    console.log("✅ New TWIN ID created successfully! DID:", realDid);

    const walletData = {
      did: realDid,
      // Note: In production, seed should not be stored locally
      // It's stored securely in Vault by the twin-service
    };

    // Save to file
    await writeFile("./twin-wallet.json", JSON.stringify(walletData, null, 2));
    console.log(
      `🔑 Wallet data saved to twin-wallet.json. Do not lose this file.`
    );
  } catch (error) {
    console.error("❌ Failed to create TWIN ID:", error.message);
    throw error;
  }
}

async function updateIdentityWithVLEILink() {
  console.log(`🚀 Updating TWIN ID to link with vLEI: ${VLEI_DID_WEBS}`);
  let walletData;
  try {
    walletData = JSON.parse(await readFile("./twin-wallet.json", "utf-8"));
  } catch (error) {
    console.error(
      `Error: Could not read wallet file. Please run 'createIdentity' first.`
    );
    return;
  }

  // Add alsoKnownAs to link with vLEI
  walletData.alsoKnownAs = [VLEI_DID_WEBS];
  await writeFile("./twin-wallet.json", JSON.stringify(walletData, null, 2));

  console.log("✅ TWIN ID updated successfully!");
  console.log(`DID: ${walletData.did}`);
  console.log(`Linked with vLEI: ${VLEI_DID_WEBS}`);
}

async function main() {
  // For automation: always create new identity and link with vLEI
  await createIdentity();
  await updateIdentityWithVLEILink();
}

main().catch(console.error);
